Click this button to run in Colab.
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ssuai/deep_learning_from_scratch/blob/master/ch05/back_prop_activation.ipynb)

In [1]:
import numpy as np

# 5.5 활성화 함수 계층 구현하기
## 5.5.1 ReLU 계층
$y=\begin{cases}
x & (x > 0)  \\ 
0 & (x \le 0)
\end{cases}$

$ \frac{\partial y}{\partial x} = \begin{cases}
1 & (x > 0)  \\ 
0 & (x \le 0)
\end{cases}$

In [2]:
# common/layers.py
class Relu:
    def __init__(self):
        self.mask = None

    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0

        return out

    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout

        return dx

In [3]:
x = np.array([[1.0, -0.5], [-2.0, 3.0]])
x

array([[ 1. , -0.5],
       [-2. ,  3. ]])

In [4]:
relu = Relu()
y = relu.forward(x)
y

array([[1., 0.],
       [0., 3.]])

In [5]:
relu.mask

array([[False,  True],
       [ True, False]])

In [6]:
relu.backward(np.ones((2,2)))

array([[1., 0.],
       [0., 1.]])

## 5.5.2 Sigmoid 계층
$y = \frac{1}{1 + e^{-x}}$


$\frac{\partial y}{\partial x} = \frac{1}{1 + e^{-x}} \frac{e^{-x}}{1 + e^{-x}} = y (1-y)$

In [7]:
# common/layers.py
class Sigmoid:
    def __init__(self):
        self.out = None

    def forward(self, x):
        def sigmoid(x):
            return 1 / (1 + np.exp(-x))    
        out = sigmoid(x)
        self.out = out
        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out

        return dx

In [8]:
x = np.array([[1.0, -0.5], [-2.0, 3.0]])
x

array([[ 1. , -0.5],
       [-2. ,  3. ]])

In [9]:
sigmoid = Sigmoid()
y = sigmoid.forward(x)
y

array([[0.73105858, 0.37754067],
       [0.11920292, 0.95257413]])

In [10]:
sigmoid.backward(1)

array([[0.19661193, 0.23500371],
       [0.10499359, 0.04517666]])